//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransAmounts
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", ConfigurationName="TransAmounts.Tamounts_Port")]
    public interface Tamounts_Port
    {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TransAmounts.Read_Result Read(TransAmounts.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<TransAmounts.Read_Result> ReadAsync(TransAmounts.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TransAmounts.ReadByRecId_Result ReadByRecId(TransAmounts.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<TransAmounts.ReadByRecId_Result> ReadByRecIdAsync(TransAmounts.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TransAmounts.ReadMultiple_Result ReadMultiple(TransAmounts.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<TransAmounts.ReadMultiple_Result> ReadMultipleAsync(TransAmounts.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TransAmounts.IsUpdated_Result IsUpdated(TransAmounts.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<TransAmounts.IsUpdated_Result> IsUpdatedAsync(TransAmounts.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TransAmounts.GetRecIdFromKey_Result GetRecIdFromKey(TransAmounts.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<TransAmounts.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(TransAmounts.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TransAmounts.Create_Result Create(TransAmounts.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<TransAmounts.Create_Result> CreateAsync(TransAmounts.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TransAmounts.CreateMultiple_Result CreateMultiple(TransAmounts.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<TransAmounts.CreateMultiple_Result> CreateMultipleAsync(TransAmounts.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TransAmounts.Update_Result Update(TransAmounts.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<TransAmounts.Update_Result> UpdateAsync(TransAmounts.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TransAmounts.UpdateMultiple_Result UpdateMultiple(TransAmounts.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<TransAmounts.UpdateMultiple_Result> UpdateMultipleAsync(TransAmounts.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TransAmounts.Delete_Result Delete(TransAmounts.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/tamounts:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<TransAmounts.Delete_Result> DeleteAsync(TransAmounts.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts")]
    public partial class Tamounts
    {
        
        private string keyField;
        
        private string codeField;
        
        private Vehicle_Type vehicle_TypeField;
        
        private bool vehicle_TypeFieldSpecified;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Vehicle_Type Vehicle_Type
        {
            get
            {
                return this.vehicle_TypeField;
            }
            set
            {
                this.vehicle_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Vehicle_TypeSpecified
        {
            get
            {
                return this.vehicle_TypeFieldSpecified;
            }
            set
            {
                this.vehicle_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts")]
    public enum Vehicle_Type
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        _x0031_4_Seater,
        
        /// <remarks/>
        _x0033_3_Seater,
        
        /// <remarks/>
        _x0032_5_Seater,
        
        /// <remarks/>
        _x0032_9_Seater,
        
        /// <remarks/>
        _41_Seater,
        
        /// <remarks/>
        _26_Seater,
        
        /// <remarks/>
        _37_Seater,
        
        /// <remarks/>
        _x0035_1_Seater,
        
        /// <remarks/>
        _x0033_4_Seater,
        
        /// <remarks/>
        _x0033_8_Seater,
        
        /// <remarks/>
        _x0034_0_Seater,
        
        /// <remarks/>
        _x0034_6_Seater,
        
        /// <remarks/>
        _x0036_0_Seater,
        
        /// <remarks/>
        _x0033_5_Seater,
        
        /// <remarks/>
        _x0033_6_Seater,
        
        /// <remarks/>
        _x0033_9_Seater,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts")]
    public partial class Tamounts_Filter
    {
        
        private Tamounts_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Tamounts_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts")]
    public enum Tamounts_Fields
    {
        
        /// <remarks/>
        Code,
        
        /// <remarks/>
        Vehicle_Type,
        
        /// <remarks/>
        Amount,
        
        /// <remarks/>
        Name,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        public string Code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=1)]
        public string Vehicle_Type;
        
        public Read()
        {
        }
        
        public Read(string Code, string Vehicle_Type)
        {
            this.Code = Code;
            this.Vehicle_Type = Vehicle_Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        public TransAmounts.Tamounts Tamounts;
        
        public Read_Result()
        {
        }
        
        public Read_Result(TransAmounts.Tamounts Tamounts)
        {
            this.Tamounts = Tamounts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        public TransAmounts.Tamounts Tamounts;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(TransAmounts.Tamounts Tamounts)
        {
            this.Tamounts = Tamounts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public TransAmounts.Tamounts_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(TransAmounts.Tamounts_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TransAmounts.Tamounts[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(TransAmounts.Tamounts[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        public TransAmounts.Tamounts Tamounts;
        
        public Create()
        {
        }
        
        public Create(TransAmounts.Tamounts Tamounts)
        {
            this.Tamounts = Tamounts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        public TransAmounts.Tamounts Tamounts;
        
        public Create_Result()
        {
        }
        
        public Create_Result(TransAmounts.Tamounts Tamounts)
        {
            this.Tamounts = Tamounts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TransAmounts.Tamounts[] Tamounts_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(TransAmounts.Tamounts[] Tamounts_List)
        {
            this.Tamounts_List = Tamounts_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TransAmounts.Tamounts[] Tamounts_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(TransAmounts.Tamounts[] Tamounts_List)
        {
            this.Tamounts_List = Tamounts_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        public TransAmounts.Tamounts Tamounts;
        
        public Update()
        {
        }
        
        public Update(TransAmounts.Tamounts Tamounts)
        {
            this.Tamounts = Tamounts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        public TransAmounts.Tamounts Tamounts;
        
        public Update_Result()
        {
        }
        
        public Update_Result(TransAmounts.Tamounts Tamounts)
        {
            this.Tamounts = Tamounts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TransAmounts.Tamounts[] Tamounts_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(TransAmounts.Tamounts[] Tamounts_List)
        {
            this.Tamounts_List = Tamounts_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TransAmounts.Tamounts[] Tamounts_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(TransAmounts.Tamounts[] Tamounts_List)
        {
            this.Tamounts_List = Tamounts_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/tamounts", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/tamounts", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface Tamounts_PortChannel : TransAmounts.Tamounts_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class Tamounts_PortClient : System.ServiceModel.ClientBase<TransAmounts.Tamounts_Port>, TransAmounts.Tamounts_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Tamounts_PortClient() : 
                base(Tamounts_PortClient.GetDefaultBinding(), Tamounts_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Tamounts_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Tamounts_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(Tamounts_PortClient.GetBindingForEndpoint(endpointConfiguration), Tamounts_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Tamounts_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Tamounts_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Tamounts_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Tamounts_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Tamounts_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransAmounts.Read_Result TransAmounts.Tamounts_Port.Read(TransAmounts.Read request)
        {
            return base.Channel.Read(request);
        }
        
        public TransAmounts.Tamounts Read(string Code, string Vehicle_Type)
        {
            TransAmounts.Read inValue = new TransAmounts.Read();
            inValue.Code = Code;
            inValue.Vehicle_Type = Vehicle_Type;
            TransAmounts.Read_Result retVal = ((TransAmounts.Tamounts_Port)(this)).Read(inValue);
            return retVal.Tamounts;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransAmounts.Read_Result> TransAmounts.Tamounts_Port.ReadAsync(TransAmounts.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransAmounts.Read_Result> ReadAsync(string Code, string Vehicle_Type)
        {
            TransAmounts.Read inValue = new TransAmounts.Read();
            inValue.Code = Code;
            inValue.Vehicle_Type = Vehicle_Type;
            return ((TransAmounts.Tamounts_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransAmounts.ReadByRecId_Result TransAmounts.Tamounts_Port.ReadByRecId(TransAmounts.ReadByRecId request)
        {
            return base.Channel.ReadByRecId(request);
        }
        
        public TransAmounts.Tamounts ReadByRecId(string recId)
        {
            TransAmounts.ReadByRecId inValue = new TransAmounts.ReadByRecId();
            inValue.recId = recId;
            TransAmounts.ReadByRecId_Result retVal = ((TransAmounts.Tamounts_Port)(this)).ReadByRecId(inValue);
            return retVal.Tamounts;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransAmounts.ReadByRecId_Result> TransAmounts.Tamounts_Port.ReadByRecIdAsync(TransAmounts.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransAmounts.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            TransAmounts.ReadByRecId inValue = new TransAmounts.ReadByRecId();
            inValue.recId = recId;
            return ((TransAmounts.Tamounts_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransAmounts.ReadMultiple_Result TransAmounts.Tamounts_Port.ReadMultiple(TransAmounts.ReadMultiple request)
        {
            return base.Channel.ReadMultiple(request);
        }
        
        public TransAmounts.Tamounts[] ReadMultiple(TransAmounts.Tamounts_Filter[] filter, string bookmarkKey, int setSize)
        {
            TransAmounts.ReadMultiple inValue = new TransAmounts.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            TransAmounts.ReadMultiple_Result retVal = ((TransAmounts.Tamounts_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransAmounts.ReadMultiple_Result> TransAmounts.Tamounts_Port.ReadMultipleAsync(TransAmounts.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransAmounts.ReadMultiple_Result> ReadMultipleAsync(TransAmounts.Tamounts_Filter[] filter, string bookmarkKey, int setSize)
        {
            TransAmounts.ReadMultiple inValue = new TransAmounts.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((TransAmounts.Tamounts_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransAmounts.IsUpdated_Result TransAmounts.Tamounts_Port.IsUpdated(TransAmounts.IsUpdated request)
        {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key)
        {
            TransAmounts.IsUpdated inValue = new TransAmounts.IsUpdated();
            inValue.Key = Key;
            TransAmounts.IsUpdated_Result retVal = ((TransAmounts.Tamounts_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransAmounts.IsUpdated_Result> TransAmounts.Tamounts_Port.IsUpdatedAsync(TransAmounts.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransAmounts.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            TransAmounts.IsUpdated inValue = new TransAmounts.IsUpdated();
            inValue.Key = Key;
            return ((TransAmounts.Tamounts_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransAmounts.GetRecIdFromKey_Result TransAmounts.Tamounts_Port.GetRecIdFromKey(TransAmounts.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key)
        {
            TransAmounts.GetRecIdFromKey inValue = new TransAmounts.GetRecIdFromKey();
            inValue.Key = Key;
            TransAmounts.GetRecIdFromKey_Result retVal = ((TransAmounts.Tamounts_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransAmounts.GetRecIdFromKey_Result> TransAmounts.Tamounts_Port.GetRecIdFromKeyAsync(TransAmounts.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransAmounts.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            TransAmounts.GetRecIdFromKey inValue = new TransAmounts.GetRecIdFromKey();
            inValue.Key = Key;
            return ((TransAmounts.Tamounts_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransAmounts.Create_Result TransAmounts.Tamounts_Port.Create(TransAmounts.Create request)
        {
            return base.Channel.Create(request);
        }
        
        public void Create(ref TransAmounts.Tamounts Tamounts)
        {
            TransAmounts.Create inValue = new TransAmounts.Create();
            inValue.Tamounts = Tamounts;
            TransAmounts.Create_Result retVal = ((TransAmounts.Tamounts_Port)(this)).Create(inValue);
            Tamounts = retVal.Tamounts;
        }
        
        public System.Threading.Tasks.Task<TransAmounts.Create_Result> CreateAsync(TransAmounts.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransAmounts.CreateMultiple_Result TransAmounts.Tamounts_Port.CreateMultiple(TransAmounts.CreateMultiple request)
        {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref TransAmounts.Tamounts[] Tamounts_List)
        {
            TransAmounts.CreateMultiple inValue = new TransAmounts.CreateMultiple();
            inValue.Tamounts_List = Tamounts_List;
            TransAmounts.CreateMultiple_Result retVal = ((TransAmounts.Tamounts_Port)(this)).CreateMultiple(inValue);
            Tamounts_List = retVal.Tamounts_List;
        }
        
        public System.Threading.Tasks.Task<TransAmounts.CreateMultiple_Result> CreateMultipleAsync(TransAmounts.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransAmounts.Update_Result TransAmounts.Tamounts_Port.Update(TransAmounts.Update request)
        {
            return base.Channel.Update(request);
        }
        
        public void Update(ref TransAmounts.Tamounts Tamounts)
        {
            TransAmounts.Update inValue = new TransAmounts.Update();
            inValue.Tamounts = Tamounts;
            TransAmounts.Update_Result retVal = ((TransAmounts.Tamounts_Port)(this)).Update(inValue);
            Tamounts = retVal.Tamounts;
        }
        
        public System.Threading.Tasks.Task<TransAmounts.Update_Result> UpdateAsync(TransAmounts.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransAmounts.UpdateMultiple_Result TransAmounts.Tamounts_Port.UpdateMultiple(TransAmounts.UpdateMultiple request)
        {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref TransAmounts.Tamounts[] Tamounts_List)
        {
            TransAmounts.UpdateMultiple inValue = new TransAmounts.UpdateMultiple();
            inValue.Tamounts_List = Tamounts_List;
            TransAmounts.UpdateMultiple_Result retVal = ((TransAmounts.Tamounts_Port)(this)).UpdateMultiple(inValue);
            Tamounts_List = retVal.Tamounts_List;
        }
        
        public System.Threading.Tasks.Task<TransAmounts.UpdateMultiple_Result> UpdateMultipleAsync(TransAmounts.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransAmounts.Delete_Result TransAmounts.Tamounts_Port.Delete(TransAmounts.Delete request)
        {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key)
        {
            TransAmounts.Delete inValue = new TransAmounts.Delete();
            inValue.Key = Key;
            TransAmounts.Delete_Result retVal = ((TransAmounts.Tamounts_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TransAmounts.Delete_Result> TransAmounts.Tamounts_Port.DeleteAsync(TransAmounts.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<TransAmounts.Delete_Result> DeleteAsync(string Key)
        {
            TransAmounts.Delete inValue = new TransAmounts.Delete();
            inValue.Key = Key;
            return ((TransAmounts.Tamounts_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Tamounts_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Tamounts_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://5.189.167.52:9992/City/WS/Mbranch/Page/Tamounts");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Tamounts_PortClient.GetBindingForEndpoint(EndpointConfiguration.Tamounts_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Tamounts_PortClient.GetEndpointAddress(EndpointConfiguration.Tamounts_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            Tamounts_Port,
        }
    }
}
