//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collateral
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals", ConfigurationName="Collateral.Collaterals_Port")]
    public interface Collaterals_Port
    {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/collaterals:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Collateral.Read_Result Read(Collateral.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/collaterals:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<Collateral.Read_Result> ReadAsync(Collateral.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/collaterals:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Collateral.ReadByRecId_Result ReadByRecId(Collateral.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/collaterals:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<Collateral.ReadByRecId_Result> ReadByRecIdAsync(Collateral.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/collaterals:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Collateral.ReadMultiple_Result ReadMultiple(Collateral.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/collaterals:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Collateral.ReadMultiple_Result> ReadMultipleAsync(Collateral.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/collaterals:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Collateral.IsUpdated_Result IsUpdated(Collateral.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/collaterals:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<Collateral.IsUpdated_Result> IsUpdatedAsync(Collateral.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/collaterals:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Collateral.GetRecIdFromKey_Result GetRecIdFromKey(Collateral.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/collaterals:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Collateral.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(Collateral.GetRecIdFromKey request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals")]
    public partial class Collaterals
    {
        
        private string keyField;
        
        private string noField;
        
        private string account_NoField;
        
        private string account_NameField;
        
        private Collateral_Type collateral_TypeField;
        
        private bool collateral_TypeFieldSpecified;
        
        private string collateralField;
        
        private string collateral_NameField;
        
        private int collateral_MultiplierField;
        
        private bool collateral_MultiplierFieldSpecified;
        
        private decimal collateral_ValueField;
        
        private bool collateral_ValueFieldSpecified;
        
        private decimal collateral_LimitField;
        
        private bool collateral_LimitFieldSpecified;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private Inward_Outward inward_OutwardField;
        
        private bool inward_OutwardFieldSpecified;
        
        private string serial_NoField;
        
        private string locationField;
        
        private string descriptionField;
        
        private System.DateTime insurance_Expiry_DateField;
        
        private bool insurance_Expiry_DateFieldSpecified;
        
        private System.DateTime deposit_DateField;
        
        private bool deposit_DateFieldSpecified;
        
        private string ownerField;
        
        private string custodianField;
        
        private System.DateTime withdrawal_DateField;
        
        private bool withdrawal_DateFieldSpecified;
        
        private bool validatedField;
        
        private bool validatedFieldSpecified;
        
        private bool dischargedField;
        
        private bool dischargedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Account_No
        {
            get
            {
                return this.account_NoField;
            }
            set
            {
                this.account_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Account_Name
        {
            get
            {
                return this.account_NameField;
            }
            set
            {
                this.account_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Collateral_Type Collateral_Type
        {
            get
            {
                return this.collateral_TypeField;
            }
            set
            {
                this.collateral_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Collateral_TypeSpecified
        {
            get
            {
                return this.collateral_TypeFieldSpecified;
            }
            set
            {
                this.collateral_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Collateral
        {
            get
            {
                return this.collateralField;
            }
            set
            {
                this.collateralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Collateral_Name
        {
            get
            {
                return this.collateral_NameField;
            }
            set
            {
                this.collateral_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Collateral_Multiplier
        {
            get
            {
                return this.collateral_MultiplierField;
            }
            set
            {
                this.collateral_MultiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Collateral_MultiplierSpecified
        {
            get
            {
                return this.collateral_MultiplierFieldSpecified;
            }
            set
            {
                this.collateral_MultiplierFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal Collateral_Value
        {
            get
            {
                return this.collateral_ValueField;
            }
            set
            {
                this.collateral_ValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Collateral_ValueSpecified
        {
            get
            {
                return this.collateral_ValueFieldSpecified;
            }
            set
            {
                this.collateral_ValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal Collateral_Limit
        {
            get
            {
                return this.collateral_LimitField;
            }
            set
            {
                this.collateral_LimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Collateral_LimitSpecified
        {
            get
            {
                return this.collateral_LimitFieldSpecified;
            }
            set
            {
                this.collateral_LimitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Inward_Outward Inward_Outward
        {
            get
            {
                return this.inward_OutwardField;
            }
            set
            {
                this.inward_OutwardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Inward_OutwardSpecified
        {
            get
            {
                return this.inward_OutwardFieldSpecified;
            }
            set
            {
                this.inward_OutwardFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Serial_No
        {
            get
            {
                return this.serial_NoField;
            }
            set
            {
                this.serial_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=15)]
        public System.DateTime Insurance_Expiry_Date
        {
            get
            {
                return this.insurance_Expiry_DateField;
            }
            set
            {
                this.insurance_Expiry_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Insurance_Expiry_DateSpecified
        {
            get
            {
                return this.insurance_Expiry_DateFieldSpecified;
            }
            set
            {
                this.insurance_Expiry_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=16)]
        public System.DateTime Deposit_Date
        {
            get
            {
                return this.deposit_DateField;
            }
            set
            {
                this.deposit_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Deposit_DateSpecified
        {
            get
            {
                return this.deposit_DateFieldSpecified;
            }
            set
            {
                this.deposit_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Custodian
        {
            get
            {
                return this.custodianField;
            }
            set
            {
                this.custodianField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=19)]
        public System.DateTime Withdrawal_Date
        {
            get
            {
                return this.withdrawal_DateField;
            }
            set
            {
                this.withdrawal_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Withdrawal_DateSpecified
        {
            get
            {
                return this.withdrawal_DateFieldSpecified;
            }
            set
            {
                this.withdrawal_DateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool Validated
        {
            get
            {
                return this.validatedField;
            }
            set
            {
                this.validatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidatedSpecified
        {
            get
            {
                return this.validatedFieldSpecified;
            }
            set
            {
                this.validatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool Discharged
        {
            get
            {
                return this.dischargedField;
            }
            set
            {
                this.dischargedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DischargedSpecified
        {
            get
            {
                return this.dischargedFieldSpecified;
            }
            set
            {
                this.dischargedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals")]
    public enum Collateral_Type
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Real_Estate,
        
        /// <remarks/>
        Plant_and_Equipment,
        
        /// <remarks/>
        Natural_Reserves,
        
        /// <remarks/>
        ShortTerm_Deposits,
        
        /// <remarks/>
        Inventory,
        
        /// <remarks/>
        Motor_Vehicle,
        
        /// <remarks/>
        Marketable_Securities,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals")]
    public enum Status
    {
        
        /// <remarks/>
        Open,
        
        /// <remarks/>
        Pending,
        
        /// <remarks/>
        Approved,
        
        /// <remarks/>
        Rejected,
        
        /// <remarks/>
        Returned,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals")]
    public enum Inward_Outward
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        In_Store,
        
        /// <remarks/>
        Returned,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals")]
    public partial class Collaterals_Filter
    {
        
        private Collaterals_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Collaterals_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals")]
    public enum Collaterals_Fields
    {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Account_No,
        
        /// <remarks/>
        Account_Name,
        
        /// <remarks/>
        Collateral_Type,
        
        /// <remarks/>
        Collateral,
        
        /// <remarks/>
        Collateral_Name,
        
        /// <remarks/>
        Collateral_Multiplier,
        
        /// <remarks/>
        Collateral_Value,
        
        /// <remarks/>
        Collateral_Limit,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Inward_Outward,
        
        /// <remarks/>
        Serial_No,
        
        /// <remarks/>
        Location,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Insurance_Expiry_Date,
        
        /// <remarks/>
        Deposit_Date,
        
        /// <remarks/>
        Owner,
        
        /// <remarks/>
        Custodian,
        
        /// <remarks/>
        Withdrawal_Date,
        
        /// <remarks/>
        Validated,
        
        /// <remarks/>
        Discharged,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/collaterals", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals", Order=0)]
        public string No;
        
        public Read()
        {
        }
        
        public Read(string No)
        {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/collaterals", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals", Order=0)]
        public Collateral.Collaterals Collaterals;
        
        public Read_Result()
        {
        }
        
        public Read_Result(Collateral.Collaterals Collaterals)
        {
            this.Collaterals = Collaterals;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/collaterals", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/collaterals", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals", Order=0)]
        public Collateral.Collaterals Collaterals;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(Collateral.Collaterals Collaterals)
        {
            this.Collaterals = Collaterals;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/collaterals", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public Collateral.Collaterals_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(Collateral.Collaterals_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/collaterals", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/collaterals", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Collateral.Collaterals[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(Collateral.Collaterals[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/collaterals", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/collaterals", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/collaterals", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/collaterals", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/collaterals", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/collaterals", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/collaterals", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface Collaterals_PortChannel : Collateral.Collaterals_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class Collaterals_PortClient : System.ServiceModel.ClientBase<Collateral.Collaterals_Port>, Collateral.Collaterals_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Collaterals_PortClient() : 
                base(Collaterals_PortClient.GetDefaultBinding(), Collaterals_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Collaterals_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Collaterals_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(Collaterals_PortClient.GetBindingForEndpoint(endpointConfiguration), Collaterals_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Collaterals_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Collaterals_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Collaterals_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Collaterals_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Collaterals_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Collateral.Read_Result Collateral.Collaterals_Port.Read(Collateral.Read request)
        {
            return base.Channel.Read(request);
        }
        
        public Collateral.Collaterals Read(string No)
        {
            Collateral.Read inValue = new Collateral.Read();
            inValue.No = No;
            Collateral.Read_Result retVal = ((Collateral.Collaterals_Port)(this)).Read(inValue);
            return retVal.Collaterals;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Collateral.Read_Result> Collateral.Collaterals_Port.ReadAsync(Collateral.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Collateral.Read_Result> ReadAsync(string No)
        {
            Collateral.Read inValue = new Collateral.Read();
            inValue.No = No;
            return ((Collateral.Collaterals_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Collateral.ReadByRecId_Result Collateral.Collaterals_Port.ReadByRecId(Collateral.ReadByRecId request)
        {
            return base.Channel.ReadByRecId(request);
        }
        
        public Collateral.Collaterals ReadByRecId(string recId)
        {
            Collateral.ReadByRecId inValue = new Collateral.ReadByRecId();
            inValue.recId = recId;
            Collateral.ReadByRecId_Result retVal = ((Collateral.Collaterals_Port)(this)).ReadByRecId(inValue);
            return retVal.Collaterals;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Collateral.ReadByRecId_Result> Collateral.Collaterals_Port.ReadByRecIdAsync(Collateral.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Collateral.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            Collateral.ReadByRecId inValue = new Collateral.ReadByRecId();
            inValue.recId = recId;
            return ((Collateral.Collaterals_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Collateral.ReadMultiple_Result Collateral.Collaterals_Port.ReadMultiple(Collateral.ReadMultiple request)
        {
            return base.Channel.ReadMultiple(request);
        }
        
        public Collateral.Collaterals[] ReadMultiple(Collateral.Collaterals_Filter[] filter, string bookmarkKey, int setSize)
        {
            Collateral.ReadMultiple inValue = new Collateral.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            Collateral.ReadMultiple_Result retVal = ((Collateral.Collaterals_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Collateral.ReadMultiple_Result> Collateral.Collaterals_Port.ReadMultipleAsync(Collateral.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Collateral.ReadMultiple_Result> ReadMultipleAsync(Collateral.Collaterals_Filter[] filter, string bookmarkKey, int setSize)
        {
            Collateral.ReadMultiple inValue = new Collateral.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((Collateral.Collaterals_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Collateral.IsUpdated_Result Collateral.Collaterals_Port.IsUpdated(Collateral.IsUpdated request)
        {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key)
        {
            Collateral.IsUpdated inValue = new Collateral.IsUpdated();
            inValue.Key = Key;
            Collateral.IsUpdated_Result retVal = ((Collateral.Collaterals_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Collateral.IsUpdated_Result> Collateral.Collaterals_Port.IsUpdatedAsync(Collateral.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Collateral.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            Collateral.IsUpdated inValue = new Collateral.IsUpdated();
            inValue.Key = Key;
            return ((Collateral.Collaterals_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Collateral.GetRecIdFromKey_Result Collateral.Collaterals_Port.GetRecIdFromKey(Collateral.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key)
        {
            Collateral.GetRecIdFromKey inValue = new Collateral.GetRecIdFromKey();
            inValue.Key = Key;
            Collateral.GetRecIdFromKey_Result retVal = ((Collateral.Collaterals_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Collateral.GetRecIdFromKey_Result> Collateral.Collaterals_Port.GetRecIdFromKeyAsync(Collateral.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Collateral.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            Collateral.GetRecIdFromKey inValue = new Collateral.GetRecIdFromKey();
            inValue.Key = Key;
            return ((Collateral.Collaterals_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Collaterals_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Collaterals_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://2.2.2.2:7047/DynamicsNAV80/WS/CRONUS International Ltd./Page/Collaterals");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Collaterals_PortClient.GetBindingForEndpoint(EndpointConfiguration.Collaterals_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Collaterals_PortClient.GetEndpointAddress(EndpointConfiguration.Collaterals_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            Collaterals_Port,
        }
    }
}
