//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iprs_services
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomError", Namespace="http://schemas.datacontract.org/2004/07/IPRSManager")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Iprs_services.FingerprintVerificationResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Iprs_services.HumanInfoCommon))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Iprs_services.HumanInfoFromBirthCert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Iprs_services.HumanInfoFromDeathCert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Iprs_services.HumanInfoFromPassport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Iprs_services.HumanInfoFromAlienCard))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Iprs_services.HumanInfoFromIDCard))]
    public partial class CustomError : object
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private bool ErrorOcurredField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ErrorOcurred
        {
            get
            {
                return this.ErrorOcurredField;
            }
            set
            {
                this.ErrorOcurredField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FingerprintVerificationResult", Namespace="http://schemas.datacontract.org/2004/07/IPRSManager")]
    public partial class FingerprintVerificationResult : Iprs_services.CustomError
    {
        
        private Iprs_services.FingerprintVerificationResultsSet ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Iprs_services.FingerprintVerificationResultsSet Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HumanInfoCommon", Namespace="http://schemas.datacontract.org/2004/07/IPRSManager")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Iprs_services.HumanInfoFromBirthCert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Iprs_services.HumanInfoFromDeathCert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Iprs_services.HumanInfoFromPassport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Iprs_services.HumanInfoFromAlienCard))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Iprs_services.HumanInfoFromIDCard))]
    public partial class HumanInfoCommon : Iprs_services.CustomError
    {
        
        private string CitizenshipField;
        
        private string ClanField;
        
        private string Date_of_BirthField;
        
        private string Date_of_DeathField;
        
        private string Ethnic_GroupField;
        
        private string FamilyField;
        
        private byte[] FingerprintField;
        
        private string First_NameField;
        
        private string GenderField;
        
        private string ID_NumberField;
        
        private string OccupationField;
        
        private string Other_NameField;
        
        private byte[] PhotoField;
        
        private string PinField;
        
        private string Place_of_BirthField;
        
        private string Place_of_DeathField;
        
        private string Place_of_LiveField;
        
        private byte[] SignatureField;
        
        private string SurnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Citizenship
        {
            get
            {
                return this.CitizenshipField;
            }
            set
            {
                this.CitizenshipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clan
        {
            get
            {
                return this.ClanField;
            }
            set
            {
                this.ClanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date_of_Birth
        {
            get
            {
                return this.Date_of_BirthField;
            }
            set
            {
                this.Date_of_BirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date_of_Death
        {
            get
            {
                return this.Date_of_DeathField;
            }
            set
            {
                this.Date_of_DeathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ethnic_Group
        {
            get
            {
                return this.Ethnic_GroupField;
            }
            set
            {
                this.Ethnic_GroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Family
        {
            get
            {
                return this.FamilyField;
            }
            set
            {
                this.FamilyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Fingerprint
        {
            get
            {
                return this.FingerprintField;
            }
            set
            {
                this.FingerprintField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name
        {
            get
            {
                return this.First_NameField;
            }
            set
            {
                this.First_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Number
        {
            get
            {
                return this.ID_NumberField;
            }
            set
            {
                this.ID_NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Occupation
        {
            get
            {
                return this.OccupationField;
            }
            set
            {
                this.OccupationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Other_Name
        {
            get
            {
                return this.Other_NameField;
            }
            set
            {
                this.Other_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Photo
        {
            get
            {
                return this.PhotoField;
            }
            set
            {
                this.PhotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pin
        {
            get
            {
                return this.PinField;
            }
            set
            {
                this.PinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place_of_Birth
        {
            get
            {
                return this.Place_of_BirthField;
            }
            set
            {
                this.Place_of_BirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place_of_Death
        {
            get
            {
                return this.Place_of_DeathField;
            }
            set
            {
                this.Place_of_DeathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Place_of_Live
        {
            get
            {
                return this.Place_of_LiveField;
            }
            set
            {
                this.Place_of_LiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HumanInfoFromBirthCert", Namespace="http://schemas.datacontract.org/2004/07/IPRSManager")]
    public partial class HumanInfoFromBirthCert : Iprs_services.HumanInfoCommon
    {
        
        private string Date_of_IssueField;
        
        private string RegOfficeField;
        
        private string Serial_NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date_of_Issue
        {
            get
            {
                return this.Date_of_IssueField;
            }
            set
            {
                this.Date_of_IssueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegOffice
        {
            get
            {
                return this.RegOfficeField;
            }
            set
            {
                this.RegOfficeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serial_Number
        {
            get
            {
                return this.Serial_NumberField;
            }
            set
            {
                this.Serial_NumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HumanInfoFromDeathCert", Namespace="http://schemas.datacontract.org/2004/07/IPRSManager")]
    public partial class HumanInfoFromDeathCert : Iprs_services.HumanInfoCommon
    {
        
        private string Date_of_IssueField;
        
        private string RegOfficeField;
        
        private string Serial_NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date_of_Issue
        {
            get
            {
                return this.Date_of_IssueField;
            }
            set
            {
                this.Date_of_IssueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegOffice
        {
            get
            {
                return this.RegOfficeField;
            }
            set
            {
                this.RegOfficeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serial_Number
        {
            get
            {
                return this.Serial_NumberField;
            }
            set
            {
                this.Serial_NumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HumanInfoFromPassport", Namespace="http://schemas.datacontract.org/2004/07/IPRSManager")]
    public partial class HumanInfoFromPassport : Iprs_services.HumanInfoCommon
    {
        
        private string Date_of_Birth_from_PassportField;
        
        private string Date_of_ExpiryField;
        
        private string Date_of_IssueField;
        
        private string Passport_NumberField;
        
        private byte[] Photo_from_PassportField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date_of_Birth_from_Passport
        {
            get
            {
                return this.Date_of_Birth_from_PassportField;
            }
            set
            {
                this.Date_of_Birth_from_PassportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date_of_Expiry
        {
            get
            {
                return this.Date_of_ExpiryField;
            }
            set
            {
                this.Date_of_ExpiryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date_of_Issue
        {
            get
            {
                return this.Date_of_IssueField;
            }
            set
            {
                this.Date_of_IssueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Passport_Number
        {
            get
            {
                return this.Passport_NumberField;
            }
            set
            {
                this.Passport_NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Photo_from_Passport
        {
            get
            {
                return this.Photo_from_PassportField;
            }
            set
            {
                this.Photo_from_PassportField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HumanInfoFromAlienCard", Namespace="http://schemas.datacontract.org/2004/07/IPRSManager")]
    public partial class HumanInfoFromAlienCard : Iprs_services.HumanInfoCommon
    {
        
        private string Date_of_ExpiryField;
        
        private string Date_of_IssueField;
        
        private string RegOfficeField;
        
        private string Serial_NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date_of_Expiry
        {
            get
            {
                return this.Date_of_ExpiryField;
            }
            set
            {
                this.Date_of_ExpiryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date_of_Issue
        {
            get
            {
                return this.Date_of_IssueField;
            }
            set
            {
                this.Date_of_IssueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegOffice
        {
            get
            {
                return this.RegOfficeField;
            }
            set
            {
                this.RegOfficeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serial_Number
        {
            get
            {
                return this.Serial_NumberField;
            }
            set
            {
                this.Serial_NumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HumanInfoFromIDCard", Namespace="http://schemas.datacontract.org/2004/07/IPRSManager")]
    public partial class HumanInfoFromIDCard : Iprs_services.HumanInfoCommon
    {
        
        private string Date_of_IssueField;
        
        private string RegOfficeField;
        
        private string Serial_NumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date_of_Issue
        {
            get
            {
                return this.Date_of_IssueField;
            }
            set
            {
                this.Date_of_IssueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegOffice
        {
            get
            {
                return this.RegOfficeField;
            }
            set
            {
                this.RegOfficeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serial_Number
        {
            get
            {
                return this.Serial_NumberField;
            }
            set
            {
                this.Serial_NumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FingerprintVerificationResultsSet", Namespace="http://schemas.datacontract.org/2004/07/IPRSManager")]
    public enum FingerprintVerificationResultsSet : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotMatch = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Match = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoFingersInDb = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Iprs_services.IServiceIPRS")]
    public interface IServiceIPRS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/Login", ReplyAction="http://tempuri.org/IServiceIPRS/LoginResponse")]
        Iprs_services.LoginResponse Login(Iprs_services.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/Login", ReplyAction="http://tempuri.org/IServiceIPRS/LoginResponse")]
        System.Threading.Tasks.Task<Iprs_services.LoginResponse> LoginAsync(Iprs_services.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/GetDataByIdCard", ReplyAction="http://tempuri.org/IServiceIPRS/GetDataByIdCardResponse")]
        Iprs_services.GetDataByIdCardResponse GetDataByIdCard(Iprs_services.GetDataByIdCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/GetDataByIdCard", ReplyAction="http://tempuri.org/IServiceIPRS/GetDataByIdCardResponse")]
        System.Threading.Tasks.Task<Iprs_services.GetDataByIdCardResponse> GetDataByIdCardAsync(Iprs_services.GetDataByIdCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/GetDataByBirthCertificate", ReplyAction="http://tempuri.org/IServiceIPRS/GetDataByBirthCertificateResponse")]
        Iprs_services.GetDataByBirthCertificateResponse GetDataByBirthCertificate(Iprs_services.GetDataByBirthCertificateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/GetDataByBirthCertificate", ReplyAction="http://tempuri.org/IServiceIPRS/GetDataByBirthCertificateResponse")]
        System.Threading.Tasks.Task<Iprs_services.GetDataByBirthCertificateResponse> GetDataByBirthCertificateAsync(Iprs_services.GetDataByBirthCertificateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/GetDataByDeathCertificate", ReplyAction="http://tempuri.org/IServiceIPRS/GetDataByDeathCertificateResponse")]
        Iprs_services.GetDataByDeathCertificateResponse GetDataByDeathCertificate(Iprs_services.GetDataByDeathCertificateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/GetDataByDeathCertificate", ReplyAction="http://tempuri.org/IServiceIPRS/GetDataByDeathCertificateResponse")]
        System.Threading.Tasks.Task<Iprs_services.GetDataByDeathCertificateResponse> GetDataByDeathCertificateAsync(Iprs_services.GetDataByDeathCertificateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/GetDataByPassport", ReplyAction="http://tempuri.org/IServiceIPRS/GetDataByPassportResponse")]
        Iprs_services.GetDataByPassportResponse GetDataByPassport(Iprs_services.GetDataByPassportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/GetDataByPassport", ReplyAction="http://tempuri.org/IServiceIPRS/GetDataByPassportResponse")]
        System.Threading.Tasks.Task<Iprs_services.GetDataByPassportResponse> GetDataByPassportAsync(Iprs_services.GetDataByPassportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/GetDataByAlienCard", ReplyAction="http://tempuri.org/IServiceIPRS/GetDataByAlienCardResponse")]
        Iprs_services.GetDataByAlienCardResponse GetDataByAlienCard(Iprs_services.GetDataByAlienCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/GetDataByAlienCard", ReplyAction="http://tempuri.org/IServiceIPRS/GetDataByAlienCardResponse")]
        System.Threading.Tasks.Task<Iprs_services.GetDataByAlienCardResponse> GetDataByAlienCardAsync(Iprs_services.GetDataByAlienCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/VerificationByIdCard", ReplyAction="http://tempuri.org/IServiceIPRS/VerificationByIdCardResponse")]
        Iprs_services.VerificationByIdCardResponse VerificationByIdCard(Iprs_services.VerificationByIdCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/VerificationByIdCard", ReplyAction="http://tempuri.org/IServiceIPRS/VerificationByIdCardResponse")]
        System.Threading.Tasks.Task<Iprs_services.VerificationByIdCardResponse> VerificationByIdCardAsync(Iprs_services.VerificationByIdCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/VerificationByPassport", ReplyAction="http://tempuri.org/IServiceIPRS/VerificationByPassportResponse")]
        Iprs_services.VerificationByPassportResponse VerificationByPassport(Iprs_services.VerificationByPassportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/VerificationByPassport", ReplyAction="http://tempuri.org/IServiceIPRS/VerificationByPassportResponse")]
        System.Threading.Tasks.Task<Iprs_services.VerificationByPassportResponse> VerificationByPassportAsync(Iprs_services.VerificationByPassportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/VerificationByAlienCard", ReplyAction="http://tempuri.org/IServiceIPRS/VerificationByAlienCardResponse")]
        Iprs_services.VerificationByAlienCardResponse VerificationByAlienCard(Iprs_services.VerificationByAlienCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/VerificationByAlienCard", ReplyAction="http://tempuri.org/IServiceIPRS/VerificationByAlienCardResponse")]
        System.Threading.Tasks.Task<Iprs_services.VerificationByAlienCardResponse> VerificationByAlienCardAsync(Iprs_services.VerificationByAlienCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/PingService", ReplyAction="http://tempuri.org/IServiceIPRS/PingServiceResponse")]
        Iprs_services.PingServiceResponse PingService(Iprs_services.PingServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIPRS/PingService", ReplyAction="http://tempuri.org/IServiceIPRS/PingServiceResponse")]
        System.Threading.Tasks.Task<Iprs_services.PingServiceResponse> PingServiceAsync(Iprs_services.PingServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string log;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pass;
        
        public LoginRequest()
        {
        }
        
        public LoginRequest(string log, string pass)
        {
            this.log = log;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool LoginResult;
        
        public LoginResponse()
        {
        }
        
        public LoginResponse(bool LoginResult)
        {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByIdCard", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByIdCardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string log;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string id_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string serial_number;
        
        public GetDataByIdCardRequest()
        {
        }
        
        public GetDataByIdCardRequest(string log, string pass, string id_number, string serial_number)
        {
            this.log = log;
            this.pass = pass;
            this.id_number = id_number;
            this.serial_number = serial_number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByIdCardResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByIdCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Iprs_services.HumanInfoFromIDCard GetDataByIdCardResult;
        
        public GetDataByIdCardResponse()
        {
        }
        
        public GetDataByIdCardResponse(Iprs_services.HumanInfoFromIDCard GetDataByIdCardResult)
        {
            this.GetDataByIdCardResult = GetDataByIdCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByBirthCertificate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByBirthCertificateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string log;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string birthCertNumber;
        
        public GetDataByBirthCertificateRequest()
        {
        }
        
        public GetDataByBirthCertificateRequest(string log, string pass, string birthCertNumber)
        {
            this.log = log;
            this.pass = pass;
            this.birthCertNumber = birthCertNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByBirthCertificateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByBirthCertificateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Iprs_services.HumanInfoFromBirthCert GetDataByBirthCertificateResult;
        
        public GetDataByBirthCertificateResponse()
        {
        }
        
        public GetDataByBirthCertificateResponse(Iprs_services.HumanInfoFromBirthCert GetDataByBirthCertificateResult)
        {
            this.GetDataByBirthCertificateResult = GetDataByBirthCertificateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByDeathCertificate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByDeathCertificateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string log;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string deathCertNumber;
        
        public GetDataByDeathCertificateRequest()
        {
        }
        
        public GetDataByDeathCertificateRequest(string log, string pass, string deathCertNumber)
        {
            this.log = log;
            this.pass = pass;
            this.deathCertNumber = deathCertNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByDeathCertificateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByDeathCertificateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Iprs_services.HumanInfoFromDeathCert GetDataByDeathCertificateResult;
        
        public GetDataByDeathCertificateResponse()
        {
        }
        
        public GetDataByDeathCertificateResponse(Iprs_services.HumanInfoFromDeathCert GetDataByDeathCertificateResult)
        {
            this.GetDataByDeathCertificateResult = GetDataByDeathCertificateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByPassport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByPassportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string log;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string id_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string passport_number;
        
        public GetDataByPassportRequest()
        {
        }
        
        public GetDataByPassportRequest(string log, string pass, string id_number, string passport_number)
        {
            this.log = log;
            this.pass = pass;
            this.id_number = id_number;
            this.passport_number = passport_number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByPassportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByPassportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Iprs_services.HumanInfoFromPassport GetDataByPassportResult;
        
        public GetDataByPassportResponse()
        {
        }
        
        public GetDataByPassportResponse(Iprs_services.HumanInfoFromPassport GetDataByPassportResult)
        {
            this.GetDataByPassportResult = GetDataByPassportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByAlienCard", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByAlienCardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string log;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string id_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string serial_number;
        
        public GetDataByAlienCardRequest()
        {
        }
        
        public GetDataByAlienCardRequest(string log, string pass, string id_number, string serial_number)
        {
            this.log = log;
            this.pass = pass;
            this.id_number = id_number;
            this.serial_number = serial_number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataByAlienCardResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataByAlienCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Iprs_services.HumanInfoFromAlienCard GetDataByAlienCardResult;
        
        public GetDataByAlienCardResponse()
        {
        }
        
        public GetDataByAlienCardResponse(Iprs_services.HumanInfoFromAlienCard GetDataByAlienCardResult)
        {
            this.GetDataByAlienCardResult = GetDataByAlienCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificationByIdCard", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerificationByIdCardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string log;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string id_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string serial_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte[][] fingerprints;
        
        public VerificationByIdCardRequest()
        {
        }
        
        public VerificationByIdCardRequest(string log, string pass, string id_number, string serial_number, byte[][] fingerprints)
        {
            this.log = log;
            this.pass = pass;
            this.id_number = id_number;
            this.serial_number = serial_number;
            this.fingerprints = fingerprints;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificationByIdCardResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerificationByIdCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Iprs_services.FingerprintVerificationResult VerificationByIdCardResult;
        
        public VerificationByIdCardResponse()
        {
        }
        
        public VerificationByIdCardResponse(Iprs_services.FingerprintVerificationResult VerificationByIdCardResult)
        {
            this.VerificationByIdCardResult = VerificationByIdCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificationByPassport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerificationByPassportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string log;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string id_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string passport_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte[][] fingerprints;
        
        public VerificationByPassportRequest()
        {
        }
        
        public VerificationByPassportRequest(string log, string pass, string id_number, string passport_number, byte[][] fingerprints)
        {
            this.log = log;
            this.pass = pass;
            this.id_number = id_number;
            this.passport_number = passport_number;
            this.fingerprints = fingerprints;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificationByPassportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerificationByPassportResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Iprs_services.FingerprintVerificationResult VerificationByPassportResult;
        
        public VerificationByPassportResponse()
        {
        }
        
        public VerificationByPassportResponse(Iprs_services.FingerprintVerificationResult VerificationByPassportResult)
        {
            this.VerificationByPassportResult = VerificationByPassportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificationByAlienCard", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerificationByAlienCardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string log;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string id_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string serial_number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte[][] fingerprints;
        
        public VerificationByAlienCardRequest()
        {
        }
        
        public VerificationByAlienCardRequest(string log, string pass, string id_number, string serial_number, byte[][] fingerprints)
        {
            this.log = log;
            this.pass = pass;
            this.id_number = id_number;
            this.serial_number = serial_number;
            this.fingerprints = fingerprints;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerificationByAlienCardResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerificationByAlienCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Iprs_services.FingerprintVerificationResult VerificationByAlienCardResult;
        
        public VerificationByAlienCardResponse()
        {
        }
        
        public VerificationByAlienCardResponse(Iprs_services.FingerprintVerificationResult VerificationByAlienCardResult)
        {
            this.VerificationByAlienCardResult = VerificationByAlienCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingService", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PingServiceRequest
    {
        
        public PingServiceRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingServiceResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PingServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool PingServiceResult;
        
        public PingServiceResponse()
        {
        }
        
        public PingServiceResponse(bool PingServiceResult)
        {
            this.PingServiceResult = PingServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceIPRSChannel : Iprs_services.IServiceIPRS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceIPRSClient : System.ServiceModel.ClientBase<Iprs_services.IServiceIPRS>, Iprs_services.IServiceIPRS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceIPRSClient() : 
                base(ServiceIPRSClient.GetDefaultBinding(), ServiceIPRSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceIPRS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceIPRSClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceIPRSClient.GetBindingForEndpoint(endpointConfiguration), ServiceIPRSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceIPRSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceIPRSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceIPRSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceIPRSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceIPRSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public Iprs_services.LoginResponse Login(Iprs_services.LoginRequest request)
        {
            return base.Channel.Login(request);
        }
        
        public System.Threading.Tasks.Task<Iprs_services.LoginResponse> LoginAsync(Iprs_services.LoginRequest request)
        {
            return base.Channel.LoginAsync(request);
        }
        
        public Iprs_services.GetDataByIdCardResponse GetDataByIdCard(Iprs_services.GetDataByIdCardRequest request)
        {
            return base.Channel.GetDataByIdCard(request);
        }
        
        public System.Threading.Tasks.Task<Iprs_services.GetDataByIdCardResponse> GetDataByIdCardAsync(Iprs_services.GetDataByIdCardRequest request)
        {
            return base.Channel.GetDataByIdCardAsync(request);
        }
        
        public Iprs_services.GetDataByBirthCertificateResponse GetDataByBirthCertificate(Iprs_services.GetDataByBirthCertificateRequest request)
        {
            return base.Channel.GetDataByBirthCertificate(request);
        }
        
        public System.Threading.Tasks.Task<Iprs_services.GetDataByBirthCertificateResponse> GetDataByBirthCertificateAsync(Iprs_services.GetDataByBirthCertificateRequest request)
        {
            return base.Channel.GetDataByBirthCertificateAsync(request);
        }
        
        public Iprs_services.GetDataByDeathCertificateResponse GetDataByDeathCertificate(Iprs_services.GetDataByDeathCertificateRequest request)
        {
            return base.Channel.GetDataByDeathCertificate(request);
        }
        
        public System.Threading.Tasks.Task<Iprs_services.GetDataByDeathCertificateResponse> GetDataByDeathCertificateAsync(Iprs_services.GetDataByDeathCertificateRequest request)
        {
            return base.Channel.GetDataByDeathCertificateAsync(request);
        }
        
        public Iprs_services.GetDataByPassportResponse GetDataByPassport(Iprs_services.GetDataByPassportRequest request)
        {
            return base.Channel.GetDataByPassport(request);
        }
        
        public System.Threading.Tasks.Task<Iprs_services.GetDataByPassportResponse> GetDataByPassportAsync(Iprs_services.GetDataByPassportRequest request)
        {
            return base.Channel.GetDataByPassportAsync(request);
        }
        
        public Iprs_services.GetDataByAlienCardResponse GetDataByAlienCard(Iprs_services.GetDataByAlienCardRequest request)
        {
            return base.Channel.GetDataByAlienCard(request);
        }
        
        public System.Threading.Tasks.Task<Iprs_services.GetDataByAlienCardResponse> GetDataByAlienCardAsync(Iprs_services.GetDataByAlienCardRequest request)
        {
            return base.Channel.GetDataByAlienCardAsync(request);
        }
        
        public Iprs_services.VerificationByIdCardResponse VerificationByIdCard(Iprs_services.VerificationByIdCardRequest request)
        {
            return base.Channel.VerificationByIdCard(request);
        }
        
        public System.Threading.Tasks.Task<Iprs_services.VerificationByIdCardResponse> VerificationByIdCardAsync(Iprs_services.VerificationByIdCardRequest request)
        {
            return base.Channel.VerificationByIdCardAsync(request);
        }
        
        public Iprs_services.VerificationByPassportResponse VerificationByPassport(Iprs_services.VerificationByPassportRequest request)
        {
            return base.Channel.VerificationByPassport(request);
        }
        
        public System.Threading.Tasks.Task<Iprs_services.VerificationByPassportResponse> VerificationByPassportAsync(Iprs_services.VerificationByPassportRequest request)
        {
            return base.Channel.VerificationByPassportAsync(request);
        }
        
        public Iprs_services.VerificationByAlienCardResponse VerificationByAlienCard(Iprs_services.VerificationByAlienCardRequest request)
        {
            return base.Channel.VerificationByAlienCard(request);
        }
        
        public System.Threading.Tasks.Task<Iprs_services.VerificationByAlienCardResponse> VerificationByAlienCardAsync(Iprs_services.VerificationByAlienCardRequest request)
        {
            return base.Channel.VerificationByAlienCardAsync(request);
        }
        
        public Iprs_services.PingServiceResponse PingService(Iprs_services.PingServiceRequest request)
        {
            return base.Channel.PingService(request);
        }
        
        public System.Threading.Tasks.Task<Iprs_services.PingServiceResponse> PingServiceAsync(Iprs_services.PingServiceRequest request)
        {
            return base.Channel.PingServiceAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceIPRS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceIPRS))
            {
                return new System.ServiceModel.EndpointAddress("http://10.1.1.5:9004/IPRSServerWCF");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceIPRSClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceIPRS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceIPRSClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceIPRS);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceIPRS,
        }
    }
}
