<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Nation_Sacco</RootNamespace>
    <CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
    <CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.14.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.14.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="9.0.10" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="6.0.*" />
    <PackageReference Include="System.ServiceModel.Http" Version="8.1.2" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="8.1.2" />
    <PackageReference Include="System.ServiceModel.Security" Version="6.0.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Logging\Logging 4\Logging 4.0.csproj" />
    <Content Include="bin\Debug\net9.0\*.xml" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="wwwroot\**" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Primitives" Version="8.1.2" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Federation" Version="8.1.2" />
  </ItemGroup>
</Project>