//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeighCon
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMLOG
    {
        public int ID { get; set; }
        public string Dayofweek { get; set; }
        public string Shift { get; set; }
        public string Year { get; set; }
        public string Weekofyear { get; set; }
        public string itemcode { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<decimal> Mass { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string Barcode { get; set; }
        public string STATUS { get; set; }
    }
}
