//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beno
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", ConfigurationName="Beno.Benovolent_Port")]
    public interface Benovolent_Port
    {
        
        // CODEGEN: Generating message contract since the wrapper name (Read_Result) of message Read_Result does not match the default value (Read)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Beno.Read_Result Read(Beno.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:Read", ReplyAction="*")]
        System.Threading.Tasks.Task<Beno.Read_Result> ReadAsync(Beno.Read request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadByRecId_Result) of message ReadByRecId_Result does not match the default value (ReadByRecId)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Beno.ReadByRecId_Result ReadByRecId(Beno.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:ReadByRecId", ReplyAction="*")]
        System.Threading.Tasks.Task<Beno.ReadByRecId_Result> ReadByRecIdAsync(Beno.ReadByRecId request);
        
        // CODEGEN: Generating message contract since the wrapper name (ReadMultiple_Result) of message ReadMultiple_Result does not match the default value (ReadMultiple)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Beno.ReadMultiple_Result ReadMultiple(Beno.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:ReadMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Beno.ReadMultiple_Result> ReadMultipleAsync(Beno.ReadMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (IsUpdated_Result) of message IsUpdated_Result does not match the default value (IsUpdated)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Beno.IsUpdated_Result IsUpdated(Beno.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:IsUpdated", ReplyAction="*")]
        System.Threading.Tasks.Task<Beno.IsUpdated_Result> IsUpdatedAsync(Beno.IsUpdated request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetRecIdFromKey_Result) of message GetRecIdFromKey_Result does not match the default value (GetRecIdFromKey)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Beno.GetRecIdFromKey_Result GetRecIdFromKey(Beno.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:GetRecIdFromKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Beno.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(Beno.GetRecIdFromKey request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Beno.Create_Result Create(Beno.Create request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:Create", ReplyAction="*")]
        System.Threading.Tasks.Task<Beno.Create_Result> CreateAsync(Beno.Create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:CreateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Beno.CreateMultiple_Result CreateMultiple(Beno.CreateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:CreateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Beno.CreateMultiple_Result> CreateMultipleAsync(Beno.CreateMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Beno.Update_Result Update(Beno.Update request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Beno.Update_Result> UpdateAsync(Beno.Update request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:UpdateMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Beno.UpdateMultiple_Result UpdateMultiple(Beno.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:UpdateMultiple", ReplyAction="*")]
        System.Threading.Tasks.Task<Beno.UpdateMultiple_Result> UpdateMultipleAsync(Beno.UpdateMultiple request);
        
        // CODEGEN: Generating message contract since the wrapper name (Delete_Result) of message Delete_Result does not match the default value (Delete)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Beno.Delete_Result Delete(Beno.Delete request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/benovolent:Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<Beno.Delete_Result> DeleteAsync(Beno.Delete request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent")]
    public partial class Benovolent
    {
        
        private string keyField;
        
        private string account_NoField;
        
        private string full_NameField;
        
        private string staff_NoField;
        
        private string member_NoField;
        
        private System.DateTime date_of_BirthField;
        
        private bool date_of_BirthFieldSpecified;
        
        private string addressField;
        
        private string telephoneField;
        
        private string faxField;
        
        private string emailField;
        
        private string iD_NoField;
        
        private decimal percentAllocationField;
        
        private bool percentAllocationFieldSpecified;
        
        private Category categoryField;
        
        private bool categoryFieldSpecified;
        
        private string residenceField;
        
        private Source sourceField;
        
        private bool sourceFieldSpecified;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private bool paidField;
        
        private bool paidFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Account_No
        {
            get
            {
                return this.account_NoField;
            }
            set
            {
                this.account_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Full_Name
        {
            get
            {
                return this.full_NameField;
            }
            set
            {
                this.full_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Staff_No
        {
            get
            {
                return this.staff_NoField;
            }
            set
            {
                this.staff_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Member_No
        {
            get
            {
                return this.member_NoField;
            }
            set
            {
                this.member_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime Date_of_Birth
        {
            get
            {
                return this.date_of_BirthField;
            }
            set
            {
                this.date_of_BirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Date_of_BirthSpecified
        {
            get
            {
                return this.date_of_BirthFieldSpecified;
            }
            set
            {
                this.date_of_BirthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Telephone
        {
            get
            {
                return this.telephoneField;
            }
            set
            {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ID_No
        {
            get
            {
                return this.iD_NoField;
            }
            set
            {
                this.iD_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal PercentAllocation
        {
            get
            {
                return this.percentAllocationField;
            }
            set
            {
                this.percentAllocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PercentAllocationSpecified
        {
            get
            {
                return this.percentAllocationFieldSpecified;
            }
            set
            {
                this.percentAllocationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Category Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CategorySpecified
        {
            get
            {
                return this.categoryFieldSpecified;
            }
            set
            {
                this.categoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Residence
        {
            get
            {
                return this.residenceField;
            }
            set
            {
                this.residenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public Source Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceSpecified
        {
            get
            {
                return this.sourceFieldSpecified;
            }
            set
            {
                this.sourceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool Paid
        {
            get
            {
                return this.paidField;
            }
            set
            {
                this.paidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaidSpecified
        {
            get
            {
                return this.paidFieldSpecified;
            }
            set
            {
                this.paidFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent")]
    public enum Category
    {
        
        /// <remarks/>
        Principal_Member,
        
        /// <remarks/>
        Spouse,
        
        /// <remarks/>
        Child,
        
        /// <remarks/>
        Parent,
        
        /// <remarks/>
        Parent_in_Law,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent")]
    public enum Source
    {
        
        /// <remarks/>
        Member_Application,
        
        /// <remarks/>
        Member_Editable,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent")]
    public enum Status
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Deceased,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent")]
    public partial class Benovolent_Filter
    {
        
        private Benovolent_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Benovolent_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent")]
    public enum Benovolent_Fields
    {
        
        /// <remarks/>
        Account_No,
        
        /// <remarks/>
        Full_Name,
        
        /// <remarks/>
        Staff_No,
        
        /// <remarks/>
        Member_No,
        
        /// <remarks/>
        Date_of_Birth,
        
        /// <remarks/>
        Address,
        
        /// <remarks/>
        Telephone,
        
        /// <remarks/>
        Fax,
        
        /// <remarks/>
        Email,
        
        /// <remarks/>
        ID_No,
        
        /// <remarks/>
        PercentAllocation,
        
        /// <remarks/>
        Category,
        
        /// <remarks/>
        Residence,
        
        /// <remarks/>
        Source,
        
        /// <remarks/>
        Status,
        
        /// <remarks/>
        Paid,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        public string Account_No;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=1)]
        public string Full_Name;
        
        public Read()
        {
        }
        
        public Read(string Account_No, string Full_Name)
        {
            this.Account_No = Account_No;
            this.Full_Name = Full_Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        public Beno.Benovolent Benovolent;
        
        public Read_Result()
        {
        }
        
        public Read_Result(Beno.Benovolent Benovolent)
        {
            this.Benovolent = Benovolent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        public Beno.Benovolent Benovolent;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(Beno.Benovolent Benovolent)
        {
            this.Benovolent = Benovolent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public Beno.Benovolent_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(Beno.Benovolent_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Beno.Benovolent[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(Beno.Benovolent[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class Create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        public Beno.Benovolent Benovolent;
        
        public Create()
        {
        }
        
        public Create(Beno.Benovolent Benovolent)
        {
            this.Benovolent = Benovolent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class Create_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        public Beno.Benovolent Benovolent;
        
        public Create_Result()
        {
        }
        
        public Create_Result(Beno.Benovolent Benovolent)
        {
            this.Benovolent = Benovolent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class CreateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Beno.Benovolent[] Benovolent_List;
        
        public CreateMultiple()
        {
        }
        
        public CreateMultiple(Beno.Benovolent[] Benovolent_List)
        {
            this.Benovolent_List = Benovolent_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class CreateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Beno.Benovolent[] Benovolent_List;
        
        public CreateMultiple_Result()
        {
        }
        
        public CreateMultiple_Result(Beno.Benovolent[] Benovolent_List)
        {
            this.Benovolent_List = Benovolent_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class Update
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        public Beno.Benovolent Benovolent;
        
        public Update()
        {
        }
        
        public Update(Beno.Benovolent Benovolent)
        {
            this.Benovolent = Benovolent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class Update_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        public Beno.Benovolent Benovolent;
        
        public Update_Result()
        {
        }
        
        public Update_Result(Beno.Benovolent Benovolent)
        {
            this.Benovolent = Benovolent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class UpdateMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Beno.Benovolent[] Benovolent_List;
        
        public UpdateMultiple()
        {
        }
        
        public UpdateMultiple(Beno.Benovolent[] Benovolent_List)
        {
            this.Benovolent_List = Benovolent_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class UpdateMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Beno.Benovolent[] Benovolent_List;
        
        public UpdateMultiple_Result()
        {
        }
        
        public UpdateMultiple_Result(Beno.Benovolent[] Benovolent_List)
        {
            this.Benovolent_List = Benovolent_List;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class Delete
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        public string Key;
        
        public Delete()
        {
        }
        
        public Delete(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/benovolent", IsWrapped=true)]
    public partial class Delete_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Result", Namespace="urn:microsoft-dynamics-schemas/page/benovolent", Order=0)]
        public bool Delete_Result1;
        
        public Delete_Result()
        {
        }
        
        public Delete_Result(bool Delete_Result1)
        {
            this.Delete_Result1 = Delete_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface Benovolent_PortChannel : Beno.Benovolent_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class Benovolent_PortClient : System.ServiceModel.ClientBase<Beno.Benovolent_Port>, Beno.Benovolent_Port
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Benovolent_PortClient() : 
                base(Benovolent_PortClient.GetDefaultBinding(), Benovolent_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Benovolent_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Benovolent_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(Benovolent_PortClient.GetBindingForEndpoint(endpointConfiguration), Benovolent_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Benovolent_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Benovolent_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Benovolent_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Benovolent_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Benovolent_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beno.Read_Result Beno.Benovolent_Port.Read(Beno.Read request)
        {
            return base.Channel.Read(request);
        }
        
        public Beno.Benovolent Read(string Account_No, string Full_Name)
        {
            Beno.Read inValue = new Beno.Read();
            inValue.Account_No = Account_No;
            inValue.Full_Name = Full_Name;
            Beno.Read_Result retVal = ((Beno.Benovolent_Port)(this)).Read(inValue);
            return retVal.Benovolent;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Beno.Read_Result> Beno.Benovolent_Port.ReadAsync(Beno.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Beno.Read_Result> ReadAsync(string Account_No, string Full_Name)
        {
            Beno.Read inValue = new Beno.Read();
            inValue.Account_No = Account_No;
            inValue.Full_Name = Full_Name;
            return ((Beno.Benovolent_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beno.ReadByRecId_Result Beno.Benovolent_Port.ReadByRecId(Beno.ReadByRecId request)
        {
            return base.Channel.ReadByRecId(request);
        }
        
        public Beno.Benovolent ReadByRecId(string recId)
        {
            Beno.ReadByRecId inValue = new Beno.ReadByRecId();
            inValue.recId = recId;
            Beno.ReadByRecId_Result retVal = ((Beno.Benovolent_Port)(this)).ReadByRecId(inValue);
            return retVal.Benovolent;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Beno.ReadByRecId_Result> Beno.Benovolent_Port.ReadByRecIdAsync(Beno.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Beno.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            Beno.ReadByRecId inValue = new Beno.ReadByRecId();
            inValue.recId = recId;
            return ((Beno.Benovolent_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beno.ReadMultiple_Result Beno.Benovolent_Port.ReadMultiple(Beno.ReadMultiple request)
        {
            return base.Channel.ReadMultiple(request);
        }
        
        public Beno.Benovolent[] ReadMultiple(Beno.Benovolent_Filter[] filter, string bookmarkKey, int setSize)
        {
            Beno.ReadMultiple inValue = new Beno.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            Beno.ReadMultiple_Result retVal = ((Beno.Benovolent_Port)(this)).ReadMultiple(inValue);
            return retVal.ReadMultiple_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Beno.ReadMultiple_Result> Beno.Benovolent_Port.ReadMultipleAsync(Beno.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Beno.ReadMultiple_Result> ReadMultipleAsync(Beno.Benovolent_Filter[] filter, string bookmarkKey, int setSize)
        {
            Beno.ReadMultiple inValue = new Beno.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((Beno.Benovolent_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beno.IsUpdated_Result Beno.Benovolent_Port.IsUpdated(Beno.IsUpdated request)
        {
            return base.Channel.IsUpdated(request);
        }
        
        public bool IsUpdated(string Key)
        {
            Beno.IsUpdated inValue = new Beno.IsUpdated();
            inValue.Key = Key;
            Beno.IsUpdated_Result retVal = ((Beno.Benovolent_Port)(this)).IsUpdated(inValue);
            return retVal.IsUpdated_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Beno.IsUpdated_Result> Beno.Benovolent_Port.IsUpdatedAsync(Beno.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<Beno.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            Beno.IsUpdated inValue = new Beno.IsUpdated();
            inValue.Key = Key;
            return ((Beno.Benovolent_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beno.GetRecIdFromKey_Result Beno.Benovolent_Port.GetRecIdFromKey(Beno.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKey(request);
        }
        
        public string GetRecIdFromKey(string Key)
        {
            Beno.GetRecIdFromKey inValue = new Beno.GetRecIdFromKey();
            inValue.Key = Key;
            Beno.GetRecIdFromKey_Result retVal = ((Beno.Benovolent_Port)(this)).GetRecIdFromKey(inValue);
            return retVal.GetRecIdFromKey_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Beno.GetRecIdFromKey_Result> Beno.Benovolent_Port.GetRecIdFromKeyAsync(Beno.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Beno.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            Beno.GetRecIdFromKey inValue = new Beno.GetRecIdFromKey();
            inValue.Key = Key;
            return ((Beno.Benovolent_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beno.Create_Result Beno.Benovolent_Port.Create(Beno.Create request)
        {
            return base.Channel.Create(request);
        }
        
        public void Create(ref Beno.Benovolent Benovolent)
        {
            Beno.Create inValue = new Beno.Create();
            inValue.Benovolent = Benovolent;
            Beno.Create_Result retVal = ((Beno.Benovolent_Port)(this)).Create(inValue);
            Benovolent = retVal.Benovolent;
        }
        
        public System.Threading.Tasks.Task<Beno.Create_Result> CreateAsync(Beno.Create request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beno.CreateMultiple_Result Beno.Benovolent_Port.CreateMultiple(Beno.CreateMultiple request)
        {
            return base.Channel.CreateMultiple(request);
        }
        
        public void CreateMultiple(ref Beno.Benovolent[] Benovolent_List)
        {
            Beno.CreateMultiple inValue = new Beno.CreateMultiple();
            inValue.Benovolent_List = Benovolent_List;
            Beno.CreateMultiple_Result retVal = ((Beno.Benovolent_Port)(this)).CreateMultiple(inValue);
            Benovolent_List = retVal.Benovolent_List;
        }
        
        public System.Threading.Tasks.Task<Beno.CreateMultiple_Result> CreateMultipleAsync(Beno.CreateMultiple request)
        {
            return base.Channel.CreateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beno.Update_Result Beno.Benovolent_Port.Update(Beno.Update request)
        {
            return base.Channel.Update(request);
        }
        
        public void Update(ref Beno.Benovolent Benovolent)
        {
            Beno.Update inValue = new Beno.Update();
            inValue.Benovolent = Benovolent;
            Beno.Update_Result retVal = ((Beno.Benovolent_Port)(this)).Update(inValue);
            Benovolent = retVal.Benovolent;
        }
        
        public System.Threading.Tasks.Task<Beno.Update_Result> UpdateAsync(Beno.Update request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beno.UpdateMultiple_Result Beno.Benovolent_Port.UpdateMultiple(Beno.UpdateMultiple request)
        {
            return base.Channel.UpdateMultiple(request);
        }
        
        public void UpdateMultiple(ref Beno.Benovolent[] Benovolent_List)
        {
            Beno.UpdateMultiple inValue = new Beno.UpdateMultiple();
            inValue.Benovolent_List = Benovolent_List;
            Beno.UpdateMultiple_Result retVal = ((Beno.Benovolent_Port)(this)).UpdateMultiple(inValue);
            Benovolent_List = retVal.Benovolent_List;
        }
        
        public System.Threading.Tasks.Task<Beno.UpdateMultiple_Result> UpdateMultipleAsync(Beno.UpdateMultiple request)
        {
            return base.Channel.UpdateMultipleAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Beno.Delete_Result Beno.Benovolent_Port.Delete(Beno.Delete request)
        {
            return base.Channel.Delete(request);
        }
        
        public bool Delete(string Key)
        {
            Beno.Delete inValue = new Beno.Delete();
            inValue.Key = Key;
            Beno.Delete_Result retVal = ((Beno.Benovolent_Port)(this)).Delete(inValue);
            return retVal.Delete_Result1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Beno.Delete_Result> Beno.Benovolent_Port.DeleteAsync(Beno.Delete request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Beno.Delete_Result> DeleteAsync(string Key)
        {
            Beno.Delete inValue = new Beno.Delete();
            inValue.Key = Key;
            return ((Beno.Benovolent_Port)(this)).DeleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Benovolent_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Benovolent_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://2.2.2.2:7047/DynamicsNAV80/WS/CRONUS International Ltd./Page/Benovolent");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Benovolent_PortClient.GetBindingForEndpoint(EndpointConfiguration.Benovolent_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Benovolent_PortClient.GetEndpointAddress(EndpointConfiguration.Benovolent_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            Benovolent_Port,
        }
    }
}
