apply plugin: 'com.android.application'

android {
    compileSdk 35
    defaultConfig {
        applicationId 'com.trimline.paul.metro'
        minSdkVersion 24
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {

        dataBinding true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    productFlavors {
    }
    namespace 'com.trimline.paul.metro'
}
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.activity:activity:1.10.1'
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation files('libs/gson-2.2.4.jar')
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.12.0'
    testImplementation 'junit:junit:4.13.2'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'com.facebook.stetho:stetho:1.6.0'
    implementation 'com.squareup.okhttp3:okhttp:5.1.0'

}
