//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RunCodunit.Embassava_CustomerStatistics {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerStatistics_Binding", Namespace="urn:microsoft-dynamics-schemas/page/customerstatistics")]
    public partial class CustomerStatistics_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomerStatistics_Service() {
            this.Url = global::RunCodunit.Properties.Settings.Default.RunCodunit_Embassava_CustomerStatistics_CustomerStatistics_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customerstatistics:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CustomerStatistics")]
        public CustomerStatistics Read(string No) {
            object[] results = this.Invoke("Read", new object[] {
                        No});
            return ((CustomerStatistics)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string No) {
            this.ReadAsync(No, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string No, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        No}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customerstatistics:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("CustomerStatistics")]
        public CustomerStatistics ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((CustomerStatistics)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customerstatistics:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CustomerStatistics[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] CustomerStatistics_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((CustomerStatistics[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(CustomerStatistics_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(CustomerStatistics_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customerstatistics:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customerstatistics:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customerstatistics:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref CustomerStatistics CustomerStatistics) {
            object[] results = this.Invoke("Create", new object[] {
                        CustomerStatistics});
            CustomerStatistics = ((CustomerStatistics)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(CustomerStatistics CustomerStatistics) {
            this.CreateAsync(CustomerStatistics, null);
        }
        
        /// <remarks/>
        public void CreateAsync(CustomerStatistics CustomerStatistics, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        CustomerStatistics}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customerstatistics:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref CustomerStatistics[] CustomerStatistics_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        CustomerStatistics_List});
            CustomerStatistics_List = ((CustomerStatistics[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(CustomerStatistics[] CustomerStatistics_List) {
            this.CreateMultipleAsync(CustomerStatistics_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(CustomerStatistics[] CustomerStatistics_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        CustomerStatistics_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customerstatistics:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref CustomerStatistics CustomerStatistics) {
            object[] results = this.Invoke("Update", new object[] {
                        CustomerStatistics});
            CustomerStatistics = ((CustomerStatistics)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(CustomerStatistics CustomerStatistics) {
            this.UpdateAsync(CustomerStatistics, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(CustomerStatistics CustomerStatistics, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        CustomerStatistics}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customerstatistics:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref CustomerStatistics[] CustomerStatistics_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        CustomerStatistics_List});
            CustomerStatistics_List = ((CustomerStatistics[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(CustomerStatistics[] CustomerStatistics_List) {
            this.UpdateMultipleAsync(CustomerStatistics_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(CustomerStatistics[] CustomerStatistics_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        CustomerStatistics_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/customerstatistics:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/customerstatistics", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerstatistics")]
    public partial class CustomerStatistics {
        
        private string keyField;
        
        private string noField;
        
        private decimal capital_BalanceField;
        
        private bool capital_BalanceFieldSpecified;
        
        private decimal deposit_BalanceField;
        
        private bool deposit_BalanceFieldSpecified;
        
        private decimal loan_BalancesField;
        
        private bool loan_BalancesFieldSpecified;
        
        private decimal insurance_DepositField;
        
        private bool insurance_DepositFieldSpecified;
        
        private decimal service_Charge_Fee_PaidField;
        
        private bool service_Charge_Fee_PaidFieldSpecified;
        
        private decimal nHIFField;
        
        private bool nHIFFieldSpecified;
        
        private decimal penaltyField;
        
        private bool penaltyFieldSpecified;
        
        private decimal operationField;
        
        private bool operationFieldSpecified;
        
        private decimal insuranceField;
        
        private bool insuranceFieldSpecified;
        
        private decimal legalField;
        
        private bool legalFieldSpecified;
        
        private decimal disbursementField;
        
        private bool disbursementFieldSpecified;
        
        private decimal outstanding_Orders_LCYField;
        
        private bool outstanding_Orders_LCYFieldSpecified;
        
        private decimal shipped_Not_Invoiced_LCYField;
        
        private bool shipped_Not_Invoiced_LCYFieldSpecified;
        
        private decimal outstanding_Invoices_LCYField;
        
        private bool outstanding_Invoices_LCYFieldSpecified;
        
        private decimal outstanding_Serv_Orders_LCYField;
        
        private bool outstanding_Serv_Orders_LCYFieldSpecified;
        
        private decimal serv_Shipped_Not_Invoiced_LCYField;
        
        private bool serv_Shipped_Not_Invoiced_LCYFieldSpecified;
        
        private decimal outstanding_Serv_Invoices_LCYField;
        
        private bool outstanding_Serv_Invoices_LCYFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public decimal Capital_Balance {
            get {
                return this.capital_BalanceField;
            }
            set {
                this.capital_BalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Capital_BalanceSpecified {
            get {
                return this.capital_BalanceFieldSpecified;
            }
            set {
                this.capital_BalanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Deposit_Balance {
            get {
                return this.deposit_BalanceField;
            }
            set {
                this.deposit_BalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Deposit_BalanceSpecified {
            get {
                return this.deposit_BalanceFieldSpecified;
            }
            set {
                this.deposit_BalanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Loan_Balances {
            get {
                return this.loan_BalancesField;
            }
            set {
                this.loan_BalancesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Loan_BalancesSpecified {
            get {
                return this.loan_BalancesFieldSpecified;
            }
            set {
                this.loan_BalancesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Insurance_Deposit {
            get {
                return this.insurance_DepositField;
            }
            set {
                this.insurance_DepositField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Insurance_DepositSpecified {
            get {
                return this.insurance_DepositFieldSpecified;
            }
            set {
                this.insurance_DepositFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Service_Charge_Fee_Paid {
            get {
                return this.service_Charge_Fee_PaidField;
            }
            set {
                this.service_Charge_Fee_PaidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Service_Charge_Fee_PaidSpecified {
            get {
                return this.service_Charge_Fee_PaidFieldSpecified;
            }
            set {
                this.service_Charge_Fee_PaidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal NHIF {
            get {
                return this.nHIFField;
            }
            set {
                this.nHIFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NHIFSpecified {
            get {
                return this.nHIFFieldSpecified;
            }
            set {
                this.nHIFFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Penalty {
            get {
                return this.penaltyField;
            }
            set {
                this.penaltyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PenaltySpecified {
            get {
                return this.penaltyFieldSpecified;
            }
            set {
                this.penaltyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperationSpecified {
            get {
                return this.operationFieldSpecified;
            }
            set {
                this.operationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Insurance {
            get {
                return this.insuranceField;
            }
            set {
                this.insuranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InsuranceSpecified {
            get {
                return this.insuranceFieldSpecified;
            }
            set {
                this.insuranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Legal {
            get {
                return this.legalField;
            }
            set {
                this.legalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LegalSpecified {
            get {
                return this.legalFieldSpecified;
            }
            set {
                this.legalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Disbursement {
            get {
                return this.disbursementField;
            }
            set {
                this.disbursementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DisbursementSpecified {
            get {
                return this.disbursementFieldSpecified;
            }
            set {
                this.disbursementFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Outstanding_Orders_LCY {
            get {
                return this.outstanding_Orders_LCYField;
            }
            set {
                this.outstanding_Orders_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Outstanding_Orders_LCYSpecified {
            get {
                return this.outstanding_Orders_LCYFieldSpecified;
            }
            set {
                this.outstanding_Orders_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Shipped_Not_Invoiced_LCY {
            get {
                return this.shipped_Not_Invoiced_LCYField;
            }
            set {
                this.shipped_Not_Invoiced_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Shipped_Not_Invoiced_LCYSpecified {
            get {
                return this.shipped_Not_Invoiced_LCYFieldSpecified;
            }
            set {
                this.shipped_Not_Invoiced_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Outstanding_Invoices_LCY {
            get {
                return this.outstanding_Invoices_LCYField;
            }
            set {
                this.outstanding_Invoices_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Outstanding_Invoices_LCYSpecified {
            get {
                return this.outstanding_Invoices_LCYFieldSpecified;
            }
            set {
                this.outstanding_Invoices_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Outstanding_Serv_Orders_LCY {
            get {
                return this.outstanding_Serv_Orders_LCYField;
            }
            set {
                this.outstanding_Serv_Orders_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Outstanding_Serv_Orders_LCYSpecified {
            get {
                return this.outstanding_Serv_Orders_LCYFieldSpecified;
            }
            set {
                this.outstanding_Serv_Orders_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Serv_Shipped_Not_Invoiced_LCY {
            get {
                return this.serv_Shipped_Not_Invoiced_LCYField;
            }
            set {
                this.serv_Shipped_Not_Invoiced_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Serv_Shipped_Not_Invoiced_LCYSpecified {
            get {
                return this.serv_Shipped_Not_Invoiced_LCYFieldSpecified;
            }
            set {
                this.serv_Shipped_Not_Invoiced_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Outstanding_Serv_Invoices_LCY {
            get {
                return this.outstanding_Serv_Invoices_LCYField;
            }
            set {
                this.outstanding_Serv_Invoices_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Outstanding_Serv_Invoices_LCYSpecified {
            get {
                return this.outstanding_Serv_Invoices_LCYFieldSpecified;
            }
            set {
                this.outstanding_Serv_Invoices_LCYFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerstatistics")]
    public partial class CustomerStatistics_Filter {
        
        private CustomerStatistics_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public CustomerStatistics_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/customerstatistics")]
    public enum CustomerStatistics_Fields {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        Capital_Balance,
        
        /// <remarks/>
        Deposit_Balance,
        
        /// <remarks/>
        Loan_Balances,
        
        /// <remarks/>
        Insurance_Deposit,
        
        /// <remarks/>
        Service_Charge_Fee_Paid,
        
        /// <remarks/>
        NHIF,
        
        /// <remarks/>
        Penalty,
        
        /// <remarks/>
        Operation,
        
        /// <remarks/>
        Insurance,
        
        /// <remarks/>
        Legal,
        
        /// <remarks/>
        Disbursement,
        
        /// <remarks/>
        Outstanding_Orders_LCY,
        
        /// <remarks/>
        Shipped_Not_Invoiced_LCY,
        
        /// <remarks/>
        Outstanding_Invoices_LCY,
        
        /// <remarks/>
        Outstanding_Serv_Orders_LCY,
        
        /// <remarks/>
        Serv_Shipped_Not_Invoiced_LCY,
        
        /// <remarks/>
        Outstanding_Serv_Invoices_LCY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerStatistics Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerStatistics)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerStatistics Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerStatistics)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerStatistics[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerStatistics[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerStatistics CustomerStatistics {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerStatistics)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerStatistics[] CustomerStatistics_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerStatistics[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerStatistics CustomerStatistics {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerStatistics)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerStatistics[] CustomerStatistics_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerStatistics[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591