using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Data.Entity;
using DevExpress.XtraBars.Ribbon;

namespace Coffee
{
    public partial class Users : Form, iCoffee, IRibbon
    {
        Navigation navigation;
       List< User> users;
        AutoweighEntities Db = new AutoweighEntities(coffee.ConnectionString());

        public Form form => this;

        public Form CardForm => null;

        public RibbonControl Ribbon => navigation.navigationribbon;

        public Formtype formtype => Formtype.List;

        public Users()
        {           
            InitializeComponent();
            if (coffee.user.Type != "Admin")
            {
                gridView1.OptionsBehavior.ReadOnly = true;
            }
            navigation = new Navigation(usersBindingSource, gridControl1, Db, true, false,"","",null,this);
            this.Controls.Add(navigation);
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext

            // Call the Load method to get the data for the given DbSet from the database.
        
            // This line of code is generated by Data Source Configuration Wizard
            users = Db.Users.ToList();
            usersBindingSource.DataSource = users;

        }

        private void saveToolStripButton_Click(object sender, EventArgs e)
        {
            gridView1.EndDataUpdate();
           Db.SaveChanges(true);
        }

        private void repositoryItemTextEdit1_Leave(object sender, EventArgs e)
        {
            // gridView1.SetRowCellValue(gridView1.FocusedRowHandle, gridView1.FocusedColumn, AutoweighEntities.GetMd5Hash(gridView1.GetFocusedDisplayText()));
        }

        public void loaddata()
        {
            //usersBindingSource.DataSource = Db.Users.ToList();
        }

        public void newitem()
        {
            usersBindingSource.AddNew();
            
        }

        public void edititem<T>(T data)
        {
             
        }

        public void deleteitem<T>(T data)
        {
            try
            {
                var d = data as User;
                if (d.Name != coffee.user.Name)
                {
                    gridView1.DeleteSelectedRows();
                    usersBindingSource.Remove(data);
                    Db.Users.Remove(data as User);
                }
            }
            catch (Exception ex) { }
        }

        private void usersBindingSource_AddingNew(object sender, AddingNewEventArgs e)
        {
            User user = new User();
            user.Date_Created = DateTime.Today;
            e.NewObject = user;
            Db.Users.Add(user);
        }
    }
}


